# .github/workflows/spotify_sync.yml
name: Spotify Playlist Sync

on:
  # Run this workflow every day at 08:00 UTC (you can change this)
  schedule:
    - cron: '0 8 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Use a specific version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install spotipy python-dotenv

      # Step 4: Create the .env and .cache files from GitHub Secrets
      - name: Create environment files from secrets
        run: |
          echo "SPOTIPY_CLIENT_ID=${{ secrets.SPOTIPY_CLIENT_ID }}" > .env
          echo "SPOTIPY_CLIENT_SECRET=${{ secrets.SPOTIPY_CLIENT_SECRET }}" >> .env
          echo "SPOTIPY_REDIRECT_URI=${{ secrets.SPOTIPY_REDIRECT_URI }}" >> .env
          echo "ARTIST_NAME=${{ secrets.ARTIST_NAME }}" >> .env
          echo "PLAYLIST_ID=${{ secrets.PLAYLIST_ID }}" >> .env
          echo "${{ secrets.SPOTIPY_CACHE }}" > .cache

      # Step 5: Run the Python script
      - name: Run the Spotify sync script
        run: python main.py
